# SPDX-License-Identifier: Apache-2.0
# Copyright 2021 Open Networking Foundation
# Copyright 2022-present Intel Corporation
#

all:
# $(@F): The file-within-directory part of the file name of the target.
	go build -o echo echo.go


clean:
	rm -rf echo

fmt:
	@go fmt ./...

